### ISSUE TITLE
Unable to move to a specific index after the component has rendered

### ISSUE THREAD

**Issue by adibaba1995** [meinto/react-native-viewpager-carousel#25]
We can display a particular page first time while the component is rendered using the initialPage prop.
But if we want to move to another page after the component has rendered, it cannot be done so.
There should be a option to move to specific index. Otherwise the library is excellent.

**Comment by meinto** [comment]
Yea, thats not documented well. I have to supplement that.

Have you tried the following.
You can access some methods via the reference of the `<TabbedPager/>` or `<ViewPager/>`.
For example `scrollToIndex` or `scrollToPage`:

```js
...

// first possibility: scroll to specific index (index starting at 0)
scrollToIndex = index => {
   this.tabbarPager.scrollToIndex(index)
}

// second possibility: scroll to specific page number (number starting at 1)
scrollToPage = number => {
   this.tabbarPager.scrollToPage(number)
}


render() {
   return (
      <TabbedPager
          ref={ref => {
            // store the reference in a instance variable of your component
            this.tabbarPager = ref
          }}
      />
   )
}

...
```

I hope this will help you.

**Comment by adibaba1995** [comment]
Thanks a lot. It worked like a charm.
