### ISSUE TITLE
OnPageChange still triggered while dragging past the screen center, even if the firePageChangeIfPassedScreenCenter is set to false

### ISSUE THREAD

**Issue by b1acKr0se** [meinto/react-native-viewpager-carousel#27]
## Expected Behavior

While dragging a page past the screen center and `firePageChangeIfPassedScreenCenter` is false, then do not fire OnPageChange.

## Actual Behavior
OnPageChange still fired even when `firePageChangeIfPassedScreenCenter` is false.

## Steps to Reproduce the Problem

Set an OnPageChange handler and put a console.log there 

## Specifications

  - Version: 0.2.12
  - Platform: ios
  - Subsystem:

**Comment by meinto** [comment]
Thanks for reporting. Issue should be resolved in v0.3.2
