### ISSUE TITLE
Lazyrender Threshold

### ISSUE THREAD

**Issue by meinto** [meinto/react-native-viewpager-carousel#5]
It should be possible to define a threshold for the lazyrender behaviour. For example not only the active page should render onPageChange. Instead for example 2 pages left and right the active page should also render onPageChange.

**Comment by SteffenHummel** [comment]
This feature would be very cool! We need this in our project for the start page :)

**Comment by fasibio** [comment]
see pullrequest #16

**Comment by meinto** [comment]
merged... thanks :)
